/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-11-28 19:03:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;

public final class adminReports_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Expense Management Reports</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("            font-family: 'Arial', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("           .navbar {\r\n");
      out.write("            background-color: #2c3e50;\r\n");
      out.write("        }\r\n");
      out.write("        .navbar-brand {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        .navbar-nav .nav-link {\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("            padding: 10px 15px;\r\n");
      out.write("        }\r\n");
      out.write("        .navbar-nav .nav-link:hover {\r\n");
      out.write("            background-color: #34495e;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        .container {\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        .header {\r\n");
      out.write("            background-color: #007bff;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        .header h2 {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .section-header {\r\n");
      out.write("            background-color: #6c757d;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-group {\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("    /* Responsive Footer */\r\n");
      out.write("    .footer {\r\n");
      out.write("      background-color: #343a40;\r\n");
      out.write("      color: white;\r\n");
      out.write("      padding: 20px;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .social-icons a {\r\n");
      out.write("      color: white;\r\n");
      out.write("      font-size: 20px;\r\n");
      out.write("      margin: 0 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Footer placement for all screen sizes */\r\n");
      out.write("    @media (max-width: 576px) {\r\n");
      out.write("      .footer {\r\n");
      out.write("        padding: 15px;\r\n");
      out.write("        font-size: 0.9rem;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .social-icons a {\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <!-- Navbar -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"#\">ExpenseManager</a>\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("                <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"admindashboard.jsp\">Home</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                   \r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"aboutus.html\">About Us</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"contactus.html\">Contact Us</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"btn btn-outline-light\" href=\"index.html\">Logout</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write("        <h2>Expense Management System Reports</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Buttons for Report Types -->\r\n");
      out.write("    <div class=\"section-header\">\r\n");
      out.write("        <h5>Generate Reports</h5>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"btn-group d-flex justify-content-around\" role=\"group\">\r\n");
      out.write("        <button onclick=\"location.href='?reportType=category'\" class=\"btn btn-primary\">Category-Wise</button>\r\n");
      out.write("        <button onclick=\"location.href='?reportType=monthly'\" class=\"btn btn-success\">Monthly</button>\r\n");
      out.write("        <button onclick=\"location.href='?reportType=user'\" class=\"btn btn-warning\">User-Wise</button>\r\n");
      out.write("        <button onclick=\"location.href='?showAllExpenses=true'\" class=\"btn btn-info\">All Expenses by User</button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Generate Reports -->\r\n");
      out.write("    ");

        String reportType = request.getParameter("reportType");
        String query = "";
        String dbURL = "jdbc:mysql://localhost:3306/expensemanagementsystem";
        String dbUser = "root";
        String dbPassword = "Root@123";

        if ("category".equalsIgnoreCase(reportType)) {
            query = "SELECT category, MAX(amount) AS maxExpense, MIN(amount) AS minExpense, AVG(amount) AS avgExpense FROM expenses GROUP BY category";
        } else if ("monthly".equalsIgnoreCase(reportType)) {
            query = "SELECT DATE_FORMAT(date, '%Y-%m') AS month, MAX(amount) AS maxExpense, MIN(amount) AS minExpense, AVG(amount) AS avgExpense FROM expenses GROUP BY month";
        } else if ("user".equalsIgnoreCase(reportType)) {
            query = "SELECT user_id, MAX(amount) AS maxExpense, MIN(amount) AS minExpense, AVG(amount) AS avgExpense FROM expenses GROUP BY user_id";
        }
    
      out.write("\r\n");
      out.write("    ");

        if (reportType != null && !query.isEmpty()) {
    
      out.write("\r\n");
      out.write("    <div class=\"section-header\">\r\n");
      out.write("        <h5>");
      out.print( reportType.substring(0, 1).toUpperCase() + reportType.substring(1) + " Report" );
      out.write("</h5>\r\n");
      out.write("    </div>\r\n");
      out.write("    <table class=\"table table-hover table-bordered\">\r\n");
      out.write("        <thead>\r\n");
      out.write("            ");

                if ("category".equalsIgnoreCase(reportType)) {
            
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>Category</th>\r\n");
      out.write("                <th>Maximum Expense</th>\r\n");
      out.write("                <th>Minimum Expense</th>\r\n");
      out.write("                <th>Average Expense</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");

                } else if ("monthly".equalsIgnoreCase(reportType)) {
            
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>Month</th>\r\n");
      out.write("                <th>Maximum Expense</th>\r\n");
      out.write("                <th>Minimum Expense</th>\r\n");
      out.write("                <th>Average Expense</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");

                } else if ("user".equalsIgnoreCase(reportType)) {
            
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>User ID</th>\r\n");
      out.write("                <th>Maximum Expense</th>\r\n");
      out.write("                <th>Minimum Expense</th>\r\n");
      out.write("                <th>Average Expense</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");

                }
            
      out.write("\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody>\r\n");
      out.write("            ");

                try (Connection conn = DriverManager.getConnection(dbURL, dbUser, dbPassword);
                     Statement stmt = conn.createStatement();
                     ResultSet rs = stmt.executeQuery(query)) {

                    while (rs.next()) {
                        if ("category".equalsIgnoreCase(reportType)) {
            
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>");
      out.print( rs.getString("category") );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( rs.getDouble("maxExpense") );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( rs.getDouble("minExpense") );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( rs.getDouble("avgExpense") );
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");

                        } else if ("monthly".equalsIgnoreCase(reportType)) {
            
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>");
      out.print( rs.getString("month") );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( rs.getDouble("maxExpense") );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( rs.getDouble("minExpense") );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( rs.getDouble("avgExpense") );
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");

                        } else if ("user".equalsIgnoreCase(reportType)) {
            
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>");
      out.print( rs.getInt("user_id") );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( rs.getDouble("maxExpense") );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( rs.getDouble("minExpense") );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( rs.getDouble("avgExpense") );
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");

                        }
                    }
                } catch (SQLException e) {
                    out.println("<tr><td colspan='4' class='text-danger text-center'>Error: " + e.getMessage() + "</td></tr>");
                }
            
      out.write("\r\n");
      out.write("        </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("    ");

        }
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Display All Expenses for a Specific User -->\r\n");
      out.write("    ");

        String showAllExpenses = request.getParameter("showAllExpenses");
        if ("true".equalsIgnoreCase(showAllExpenses)) {
    
      out.write("\r\n");
      out.write("    <div class=\"section-header\">\r\n");
      out.write("        <h5>All Expenses for Specific User</h5>\r\n");
      out.write("    </div>\r\n");
      out.write("    <form method=\"get\" action=\"\">\r\n");
      out.write("        <div class=\"row mb-3\">\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("                <label for=\"userId\" class=\"form-label\">User ID</label>\r\n");
      out.write("                <input type=\"text\" name=\"userId\" id=\"userId\" class=\"form-control\" placeholder=\"Enter User ID\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6 d-flex align-items-end\">\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary\">Show Expenses</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("    ");

            String userId = request.getParameter("userId");
            if (userId != null && !userId.trim().isEmpty()) {
                String userQuery = "SELECT expense_id, budget_id, amount, date, category, description, created_at FROM expenses WHERE user_id = ?";
                try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/expensemanagementsystem", "root", "Root@123");
                     PreparedStatement pstmt = conn.prepareStatement(userQuery)) {

                    pstmt.setInt(1, Integer.parseInt(userId));
                    ResultSet rs = pstmt.executeQuery();
    
      out.write("\r\n");
      out.write("    <table class=\"table table-hover table-bordered\">\r\n");
      out.write("        <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>Expense ID</th>\r\n");
      out.write("                <th>Budget ID</th>\r\n");
      out.write("                <th>Amount</th>\r\n");
      out.write("                <th>Date</th>\r\n");
      out.write("                <th>Category</th>\r\n");
      out.write("                <th>Description</th>\r\n");
      out.write("                <th>Created At</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody>\r\n");
      out.write("            ");

                    boolean hasData = false;
                    while (rs.next()) {
                        hasData = true;
            
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>");
      out.print( rs.getInt("expense_id") );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( rs.getInt("budget_id") );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( rs.getDouble("amount") );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( rs.getDate("date") );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( rs.getString("category") );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( rs.getString("description") );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( rs.getTimestamp("created_at") );
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");

                    }
                    if (!hasData) {
            
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td colspan=\"7\" class=\"text-center\">No expenses found for User ID ");
      out.print( userId );
      out.write(".</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");

                    }
                } catch (SQLException e) {
                    out.println("<tr><td colspan='7' class='text-danger text-center'>Error: " + e.getMessage() + "</td></tr>");
                }
            }
            
      out.write("\r\n");
      out.write("        </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("    ");

        }
    
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Footer Section -->\r\n");
      out.write("  <footer class=\"footer mt-5\">\r\n");
      out.write("    <div class=\"container text-center\">\r\n");
      out.write("      <p>&copy; 2024 Expense Management System</p>\r\n");
      out.write("      <div class=\"social-icons\">\r\n");
      out.write("        <a href=\"https://facebook.com\" target=\"_blank\"><i class=\"fab fa-facebook\"></i></a>\r\n");
      out.write("        <a href=\"https://instagram.com\" target=\"_blank\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("        <a href=\"https://linkedin.com\" target=\"_blank\"><i class=\"fab fa-linkedin\"></i></a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("<!-- Bootstrap JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
