/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-11-17 18:32:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class RegistrationForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Register</title>\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- FontAwesome Icons -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("    <!-- SweetAlert2 for alerts -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("            background: linear-gradient(135deg, #e0eafc, #cfdef3);\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        .register-container {\r\n");
      out.write("            max-width: 500px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("            box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .register-card h3 {\r\n");
      out.write("            color: #007bff;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-size: 1.8rem;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("        .register-btn {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            background-color: #007bff;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            transition: background-color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .register-btn:hover {\r\n");
      out.write("            background-color: #0056b3;\r\n");
      out.write("        }\r\n");
      out.write("        .form-group i {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            left: 15px;\r\n");
      out.write("            transform: translateY(-50%);\r\n");
      out.write("            color: #007bff;\r\n");
      out.write("        }\r\n");
      out.write("        .form-group input,\r\n");
      out.write("        .form-group select {\r\n");
      out.write("            padding-left: 40px;\r\n");
      out.write("            height: 45px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            border: 1px solid #ddd;\r\n");
      out.write("        }\r\n");
      out.write("        .form-group input:focus,\r\n");
      out.write("        .form-group select:focus {\r\n");
      out.write("            border-color: #007bff;\r\n");
      out.write("            box-shadow: 0 0 8px rgba(0, 123, 255, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("        .social-media-icons {\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .social-media-icons a {\r\n");
      out.write("            font-size: 25px;\r\n");
      out.write("            margin: 0 10px;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("        .social-media-icons a:hover {\r\n");
      out.write("            color: #007bff;\r\n");
      out.write("        }\r\n");
      out.write("        .login-link {\r\n");
      out.write("            display: block;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        .login-link a {\r\n");
      out.write("            color: #007bff;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("        .login-link a:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"register-container\">\r\n");
      out.write("    <div class=\"card register-card\">\r\n");
      out.write("        <h3 class=\"text-center mb-4\">Sign Up</h3>\r\n");
      out.write("        <form id=\"registerForm\" action=\"Registrationservlet\" method=\"POST\">\r\n");
      out.write("            <div class=\"form-group position-relative\">\r\n");
      out.write("                <i class=\"fas fa-user\"></i>\r\n");
      out.write("                <label for=\"username\" class=\"sr-only\">Username</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"username\" placeholder=\"Username\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group position-relative\">\r\n");
      out.write("                <i class=\"fas fa-envelope\"></i>\r\n");
      out.write("                <label for=\"email\" class=\"sr-only\">Email</label>\r\n");
      out.write("                <input type=\"email\" class=\"form-control\" name=\"email\" placeholder=\"Email\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group position-relative\">\r\n");
      out.write("                <i class=\"fas fa-lock\"></i>\r\n");
      out.write("                <label for=\"password\" class=\"sr-only\">Password</label>\r\n");
      out.write("                <input type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"Password\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group position-relative\">\r\n");
      out.write("                <i class=\"fas fa-calendar-alt\"></i>\r\n");
      out.write("                <label for=\"birthdate\" class=\"sr-only\">Birthdate</label>\r\n");
      out.write("                <input type=\"date\" class=\"form-control\" name=\"birthdate\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group position-relative\">\r\n");
      out.write("                <i class=\"fas fa-venus-mars\"></i>\r\n");
      out.write("                <label for=\"gender\" class=\"sr-only\">Gender</label>\r\n");
      out.write("                <select class=\"form-control\" name=\"gender\" required>\r\n");
      out.write("                    <option value=\"\" disabled selected>Gender</option>\r\n");
      out.write("                    <option value=\"male\">Male</option>\r\n");
      out.write("                    <option value=\"female\">Female</option>\r\n");
      out.write("                    <option value=\"other\">Other</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group position-relative\">\r\n");
      out.write("                <i class=\"fas fa-user-tag\"></i>\r\n");
      out.write("                <label for=\"role\" class=\"sr-only\">Role</label>\r\n");
      out.write("                <select class=\"form-control\" name=\"role\" required>\r\n");
      out.write("                    <option value=\"\" disabled selected>Select Role</option>\r\n");
      out.write("                    <option value=\"user\">User</option>\r\n");
      out.write("                    <option value=\"admin\">Admin</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button type=\"submit\" class=\"btn register-btn\">Register</button>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"login-link\">\r\n");
      out.write("            <p>Already have an account? <a href=\"login.jsp\">Login here</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"social-media-icons\">\r\n");
      out.write("            <a href=\"#\" class=\"fab fa-facebook-square\"></a>\r\n");
      out.write("            <a href=\"#\" class=\"fab fa-google\"></a>\r\n");
      out.write("            <a href=\"#\" class=\"fab fa-twitter\"></a>\r\n");
      out.write("            <a href=\"#\" class=\"fab fa-linkedin\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
 String status = (String) request.getAttribute("status"); 
      out.write("\r\n");
      out.write("    <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("    ");
 if ("userexists".equals(status)) { 
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            swal(\"Error\", \"User already exists. Please try a different email.\", \"error\");\r\n");
      out.write("        </script>\r\n");
      out.write("    ");
 } else if ("success".equals(status)) { 
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            swal(\"Congrats\", \"Account Created Successfully\", \"success\");\r\n");
      out.write("        </script>\r\n");
      out.write("    ");
 } else if ("failed".equals(status)) { 
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            swal(\"Error\", \"Registration failed. Please try again.\", \"error\");\r\n");
      out.write("        </script>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
